### ISSUE TITLE
rpecanapi: `ping()` and `get.status()` Functions Return 'Server Not Responding' Error When Connecting to PEcAn Server

### ISSUE THREAD

**Issue by Sweetdevil144** [PecanProject/rpecanapi#21]
### Bug Description

When attempting to use the `rpecanapi` package to connect to the PEcAn server, the functions `ping()` and `get.status()` return "Sorry! Server not responding.", which is the default `error` response in the `tryCatch` statement.

### To Reproduce

1. Load the `rpecanapi` library.
2. Connect to the PEcAn server using the `connect()` function with the appropriate URL, username, and password.
3. Call the `ping()` or `get.status()` function.

## Expected behavior

I expect the `ping()` and `get.status()` functions to return a response from the PEcAn server indicating its status as follows : 

For the `ping(server)` command :

```r
ping(server)

#> $request
#> [1] "ping"

#> $response
#> [1] "pong"
```

For the `get.status(server)` command :

```r
get.status(server)

#> $pecan_details$version
#> [1] "1.7.0"

#> $pecan_details$branch
#> [1] "develop"

#> $pecan_details$gitsha1
#> [1] "unknown"

#> $host_details$hostid
#> [1] 99

#> $host_details$hostname
#> [1] ""

#> $host_details$start
#> [1] 99000000000

#> $host_details$end
#> [1] 99999999999

#> $host_details$sync_url
#> [1] ""

#> $host_details$sync_contact
#> [1] ""

#> $host_details$authentication_required
#> "TRUE"
```

## Screenshots

<img width="541" alt="Screenshot 2024-03-05 at 11 07 34 AM" src="https://github.com/PecanProject/rpecanapi/assets/117591942/8ab09c4a-4b8d-4b79-b41f-50e731873a0f">

## Machine (please complete the following information):

 - Server : Localhost
 - OS: MacOS

## Additional context

I'm running the R session on a Linux machine and attempting to connect to a PEcAn server running locally on port 8000. The server is expected to be responsive as per its normal behavior.

**Comment by infotroph** [comment]
Can you confirm what hostname and port bindings your local PEcAn server are using? My local Docker setup responds to pings sent to `http://pecan.localhost:80` but not to `http://localhost:8000`, and I think that may now be the default unless you specifically change it.

**Comment by Sweetdevil144** [comment]
That's indeed true. I forgot that our localhost is now moved to `http://pecan.localhost:80` instead of `http://localhost:8000`. I guess the documentations are outdated now. I'll update them now so others don't face a similar problem. Thanks for help @infotroph :)
